set -gx WORKSPACE_DIR $HOME/Workspace
set -gx GOPATH $HOME/.local/go
set -gx ANSIBLE_CONFIG $WORKSPACE_DIR/ansible/ansible.cfg
set -gx ANSIBLE_INVENTORY $WORKSPACE_DIR/ansible/home
set -gx ANSIBLE_VAULT_PASSWORD_FILE $HOME/.local/scripts/ansible-password-file.sh
set -gx GIT_ADDR ssh://git.service.saturn.consul:2222
set -gx CONSUL_HTTP_ADDR http://mimas.saturn.sol:8500
set -gx NOMAD_ADDR http://nomad.service.saturn.consul:4646
set -gx NOMAD_REGION sol
set -gx VAULT_ADDR http://vault.service.saturn.consul:8200/
