format = """
$time\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$line_break\
$username\
$character"""

right_format = """$cmd_duration"""
add_newline = false

[time]
disabled = false
format = "[\\[$time\\]](bold red) "

[username]
show_always = true
format = "[$user](blue)"

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname:](bold black)'

[directory]
truncation_length = 1
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = '[$path]($style)[$read_only]($read_only_style)'
style = "bold black"

[character]
success_symbol = "[ ❯](bold green)"
error_symbol = "[ ❯](bold red)"

[git_branch]
format = " [$symbol$branch]($style)"
symbol = " "

[git_commit]
format = ' [\($hash$tag\)]($style) '

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
