#!/bin/bash

GOTO_CACHE_FILE="${HOME}/.local/goto/cache"

function goto::find() {
    (
        \grep "${@}\$" "${GOTO_CACHE_FILE}" 2>/dev/null &&
            1>&2 echo -n 'cached'
    ) ||
        (
            1>&2 echo -n 'searching... ' 
            \find "${CTHULHU_DIR}" -type d -name "$@" -not -path '*/.git/*' 
        )
}

function goto::cache() {
    \grep "${@}$" "${GOTO_CACHE_FILE}" 1>/dev/null 2>&1 ||
        (
            1>&2 echo -n 'discovered' &&
            echo "${@}" >> "${GOTO_CACHE_FILE}"
        )
}

function goto::which() {
    DIRS=("${@}")
    1>&2 echo -n "which? "
    for d in "${DIRS[@]}"; do
        echo "$d"
    done | fzf
}

function goto::cd() {
    goto::cache "${@}"
    1>&2 echo " -> ${@}"
    cd "${@}"
}

function goto::dump() {
    rm -v "r${GOTO_CACHE_FILE}"
}

function goto {
    DIRS=($(goto::find "$@"))

    if [[ "${#DIRS[@]}" -eq 0 ]]; then
        1>&2 echo "not found"
        return
    fi

    DIR="${DIRS}"
    if [[ "${#DIRS[@]}" -gt 1 ]]; then
        DIR=$(goto::which "${DIRS[@]}")
    fi
    
    if [[ "${DIR}" == "" ]]; then
        1>&2 echo "canceled"
        return
    fi

    goto::cd "${DIR}"
}

alias g2='goto'

