#!/usr/bin/env python3

import json
import os
import re
import requests
import sys

def qute_command(command):
    with open(os.environ['QUTE_FIFO'], 'w') as fifo:
        fifo.write(command + '\n')
        fifo.flush()

def message(level, message):
    qute_command(f'message-{level} "{message}"')

job_id = "youtube-dl"
valid_url = re.compile('.*youtube\.com.*')

download_url = os.environ["QUTE_URL"]
nomad_address = os.environ["NOMAD_ADDR"]

if not valid_url.match(download_url):
    message("error", f"{download_url} is not a youtube url")
    sys.exit(2)

dispatch_url = f"{nomad_address}/v1/job/{job_id}/dispatch"

payload = {
    "Meta": {
        "url": download_url,
    }
}

r = requests.post(dispatch_url, data=json.dumps(payload))

print(r.json())

message("info", f"added {download_url} to download queue")
